### ISSUE TITLE
Color issue on wuxiaworld.com

### ISSUE THREAD

**Issue by Moonstarx** [dipu-bd/lightnovel-crawler#1363]
Website URL: https://www.wuxiaworld.com/
Crawler version: latest
App used to read epub: Calibre reader

My early chapters of epub are fine but in later chapters, the colors start to change, please see the screenshot to understand the situation better. This problem only occurred on wuxiaworld.com and did not happen on other sites. Also only happens in the novels with many chapters on wuxiaworld. Few examples: https://www.wuxiaworld.com/novel/absolute-resonance
https://www.wuxiaworld.com/novel/overgeared
https://www.wuxiaworld.com/novel/second-life-ranker
https://www.wuxiaworld.com/novel/divine-throne-of-primordial-blood

Early chapters epub:
![wuxiaworld 1](https://user-images.githubusercontent.com/50137777/170748760-e1dffd37-361b-43bb-ac5a-b127170b84de.png)

Later chapters epub:
![wuxiaworld 2](https://user-images.githubusercontent.com/50137777/170749073-817def0e-662f-4b88-8d50-f2aa4a2e028c.png)

On a side note can we get an option to save email/pass for wuxiaworld so we do not need to enter that information again? cause the site does not work without using an account anymore.

**Comment by dipu-bd** [comment]
> My early chapters of epub are fine but in later chapters, the colors start to change, please see the screenshot to understand the situation better

This should be easy to fix. 

> On a side note can we get an option to save email/pass for wuxiaworld so we do not need to enter that information again? cause the site does not work without using an account anymore.

I already found a way to enable login. Follow #1360

**Comment by dipu-bd** [comment]
fixed

**Comment by budikesuma** [comment]
@dipu-bd 
Hello devs...

Sorry if bothering. 
Ah, no... don't do that devs. It also removes important information like footnote ids and links. Useful links also get deleted. 

A solution might be to implement a script to only delete spans that contain `span style="color: rgb(0, 0, 0); background-color: transparent; `. 

I really need that information to clearly read what the author/translator is trying to convey. 

Please put it back as it was if you can't just remove the color element, please don't remove those:  `span class, span id, div class, div id, a href` etc that do not set the style of the pages/contents.
🙏🙏🙏

**Comment by budikesuma** [comment]
@Moonstarx 

I will guide you if you don't know what to do.
I have an epub that also has black font color and dark background on chapter 150 onwards (you can see it in `<span style="color:xxxxxx;"` ).

We will see how Calibre handles it with the theme color settings that we can set at will.
.
.
![20220531_061348~2](https://user-images.githubusercontent.com/50254552/171068547-c9d7eba0-5e46-4117-87d1-6cff2e0a0384.jpg)
.
![20220531_060230~2](https://user-images.githubusercontent.com/50254552/171068581-e1bd3ef4-91c9-48e6-8111-9581d3dab2aa.jpg)
.
![20220531_060653~2](https://user-images.githubusercontent.com/50254552/171068635-23e14e6d-0368-4417-aa13-a177fd2a44ac.jpg)
.
![20220531_060706~2](https://user-images.githubusercontent.com/50254552/171068662-b2752582-58fa-4784-8d9a-d6abda72925c.jpg)
.
![20220531_060747~2](https://user-images.githubusercontent.com/50254552/171068701-a19a65e3-f827-4a34-b31a-69a3d1376ac7.jpg)
.
![20220531_060345~2](https://user-images.githubusercontent.com/50254552/171068732-209100c4-a7fd-469f-9d97-3b561f8bf4df.jpg)
.
![20220531_060006~2](https://user-images.githubusercontent.com/50254552/171068758-e7e600fb-0249-447f-986b-002c36290e24.jpg)
.
![20220531_060845~2](https://user-images.githubusercontent.com/50254552/171068805-7337af94-71b6-43f2-a280-a54ad683296f.jpg)

**Comment by dipu-bd** [comment]
> Those elements are useful when I want to create clickable footnotes(crosslink/Pop-up footnotes) on epub files.

okay, good point. i will update it again.

**Comment by budikesuma** [comment]
@dipu-bd 
> 
> okay, good point. I will update it again.

Wait... 😅, you're not thinking of removing all the elements contained in the `<span style` right?

   I suddenly remembered that there are `italic` fonts and `bold` fonts inside that `<span style`. These cannot be removed.

   The best solution I can think of is to use RegEx to change only certain `colors` to `auto`.

I don't know if this is correct or not in python. For example:

```
content = content.replace('color:[^><:;]*?;', 'color: auto;')
```

This script should change all font colors as well as background-colors to automatic.

Thanks for your attention.

**Comment by dipu-bd** [comment]
i will just remove all attributes from the html tags. it will remove styles

**Comment by budikesuma** [comment]
@dipu-bd 
> i will just remove all attributes from the html tags. it will remove styles, font size etc

   Can I lock the `wuxiacom.py` source file to `read only` on termux? That way termux can only read old `wuxiacom.py` file without updating them? Can it still scrape the wuxiaworld site properly?

**Comment by budikesuma** [comment]
@dipu-bd 
Great, termux can read the `read-only` file, but it always has to enter the login info. Can I paste the login info into `wuxiacom.py`? How to do it?

**Comment by dipu-bd** [comment]
fixed

**Comment by budikesuma** [comment]
> fixed

@dipu-bd 

Hi dev,
Sorry for disturbing, but the changes still failed to maintain the original information of the wuxiaworld.com website. 
Like the tags `<a href, <a class, <a id, etc. are just shortened to `<a>`. Likewise, `<span id, <span class, <span style` etc are shortened to `<span>`. 
So scraping wuxiaworld.com becomes no different in result than scraping on an aggregator site. 
And this is what I avoid the most. Hopefully the developer is willing to revert back to the old `wuxiacom.py`.

Many thanks for your hardworking...🙏🏼
.
Please check this file:

[Chapter 99.html.txt](https://github.com/dipu-bd/lightnovel-crawler/files/8839003/Chapter.99.html.txt)

.
![Screenshot_20220605-045837_MiXplorer](https://user-images.githubusercontent.com/50254552/172027021-3cab44d4-d8cd-48a5-a404-02861084fea9.jpg)

**Comment by budikesuma** [comment]
I suspected that perhaps the `<img src` tag that actually contained the image would end up with no image, as the data had been truncated.

**Comment by dipu-bd** [comment]
I guess you want to keep the attributes of `<a>` tags too.

I don't have the time and patience to check 10-20 examples of html pages and decide which tags and attribute to keep to solve this issue. I will revert it back to original one.

But to solve this issue, I am gonna remove the style tags from all tags. Let me know if this causes any problem.

**Comment by budikesuma** [comment]
> I will revert it back to original one.
> 
> But to solve this issue, I am gonna remove the `style` attribute from all tags. Let me know if this causes any problem.


@dipu-bd ,thanks devs for your hardworking...🙏🏼🙏🏼

I have investigated some random chapters (not mentioned because there are many random chapters), and the result is that many other tags that are not `<span style` but contain styles are also deleted, some tags contain images as well.

Since this is only a font color issue, could it be possible to target only the font color.

Having investigated many chapters of WuxiaWorld, I know that there are only 2 types of dark colors supported by WuxiaWorld, namely:  `color: rgb(0, 0, 0);` and `color: rgba(0, 0, 0, 1);`

Can we just implement the color replacement of those fonts to be `auto`?
For example:

```
            content = content.replace('color: rgb(0, 0, 0);', 'color: auto;')

            content = content.replace('color: rgba(0, 0, 0, 1);', 'color: auto;')
```

**Hopefully it can be applied in python.**🙏🏼

**Comment by budikesuma** [comment]
@dipu-bd 

Don't know if the `code` placement was correct or not, but at least it gave positive results.

Please check this old `wuxiacom.py` file that I have added the `code` written in the post above, is it placed correctly or not?

I executed the `wuxiacom.py` with `pyDroid3` on my phone, and it fixed only the font colors and backgrounds, no more removing tags or other styles...

**File `wuxiacom.py` uploaded: **
.
[wuxiacom.py.txt](https://github.com/dipu-bd/lightnovel-crawler/files/8844113/wuxiacom.py.txt)
.
.

![Screenshot_20220606-181722_MiXplorer](https://user-images.githubusercontent.com/50254552/172153778-3e7862cb-8833-4667-b802-455a9388ba4b.jpg)
.
.
![Screenshot_20220606-180254_MiXplorer](https://user-images.githubusercontent.com/50254552/172153914-2bcee6d2-4e9e-43d5-9464-23c582cdcd90.jpg)
