### ISSUE TITLE
Fix this bug source: wuxiaworld.com

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1510]
@dipu-bd 
Hello dev,

The latest `wuxiacom` update was not working on termux, pydroid3 and Google colab (BUG: Suddenly exit after enter the url link without warning/error first).

Then I experimented with the `old wuxiacom` file and it worked. (Note: I just copied all the text in the `old wuxiacom`, and pasted all the text into the `new wuxiacom` file on the pydroid3 system after the update).

Would you be willing to take a quick look to see what's wrong with the latest update?

I have included the file, if you don't have a backup (Edit: sorry, can't upload that such file on github, I'll pasted all the text file here).

。Script text from `old wuxiacom.py`。
```
# -*- coding: utf-8 -*-
import json
import logging
import re

from bs4 import Comment

from lncrawl.core.crawler import Crawler

logger = logging.getLogger(__name__)

from pyease_grpc import RpcSession


class WuxiaComCrawler(Crawler):
    base_url = ['https://www.wuxiaworld.com/']

    def initialize(self):
        self.home_url = 'https://www.wuxiaworld.com'
        self.grpc = RpcSession.from_descriptor(WUXIWORLD_PROTO)
        self.cleaner.bad_css.clear()
        self.cleaner.bad_tags.add('hr')
        self.bearer_token = None
    # end def

    def login(self, email: str, password: str) -> None:
        self.bearer_token = email + ' ' + password
    # end def

    def read_novel_info(self):
        slug = re.findall(r'/novel/([^/]+)', self.novel_url)[0]
        logger.debug('Novel slug: %s', slug)

        response = self.grpc.request(
            'https://api.wuxiaworld.com/wuxiaworld.api.v2.Novels/GetNovel',
            {'slug': slug},
            headers={ 'authorization': self.bearer_token, }
        )
        response.raise_for_status()
        assert response.single
        novel = response.single['item']

        self.novel_title = novel['name']
        logger.info('Novel title = %s', self.novel_title)
        
        self.novel_cover = novel['coverUrl']
        logger.info('Novel cover = %s', self.novel_cover)

        self.novel_author = novel['authorName']
        logger.info('Novel author = %s', self.novel_author)

        response = self.grpc.request(
            'https://api.wuxiaworld.com/wuxiaworld.api.v2.Chapters/GetChapterList',
            {'novelId': novel['id']},
            headers={ 'authorization': self.bearer_token, }
        )
        response.raise_for_status()
        assert response.single
        volumes = response.single['items']
        
        for group in sorted(volumes, key=lambda x: x.get('order', 0)):
            vol_id = len(self.volumes) + 1
            self.volumes.append({
                'id': vol_id,
                'title': group['title'],
            })
            for chap in group['chapterList']:
                chap_id = len(self.chapters) + 1
                self.chapters.append({
                    'id': chap_id,
                    'volume': vol_id,
                    'title': chap['name'],
                    'entityId': chap['entityId'],
                    'url': 'https://www.wuxiaworld.com/novel/%s/%s' % (slug, chap['slug']),
                })
            # end for
        # end for
    # end def

    def download_chapter_body(self, chapter):
        response = self.grpc.request(
            'https://api.wuxiaworld.com/wuxiaworld.api.v2.Chapters/GetChapter',
            {'chapterProperty': {'chapterId': chapter['entityId']}},
            headers={ 'authorization': self.bearer_token, }
        )
        response.raise_for_status()
        assert response.single

        chapter = response.single['item']['content']

        if 'translatorThoughts' in response.single['item']:
            chapter += '<hr/>'
            chapter += "<blockquote><b>Translator's Thoughts</b>"
            chapter += response.single['item']['translatorThoughts']
            chapter += "</blockquote>"

        chapter = re.sub(r'(background-)?color: [^\\";]+', '', chapter)
        return chapter
    # end def
# end class


WUXIWORLD_PROTO=json.loads('''
{"file": [{"name": "google/protobuf/wrappers.proto", "package": "google.protobuf", "messageType": [{"name": "DoubleValue", "field": [{"name": "value", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_DOUBLE", "jsonName": "value"}]}, {"name": "FloatValue", "field": [{"name": "value", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_FLOAT", "jsonName": "value"}]}, {"name": "Int64Value", "field": [{"name": "value", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_INT64", "jsonName": "value"}]}, {"name": "UInt64Value", "field": [{"name": "value", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_UINT64", "jsonName": "value"}]}, {"name": "Int32Value", "field": [{"name": "value", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_INT32", "jsonName": "value"}]}, {"name": "UInt32Value", "field": [{"name": "value", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_UINT32", "jsonName": "value"}]}, {"name": "BoolValue", "field": [{"name": "value", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_BOOL", "jsonName": "value"}]}, {"name": "StringValue", "field": [{"name": "value", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_STRING", "jsonName": "value"}]}, {"name": "BytesValue", "field": [{"name": "value", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_BYTES", "jsonName": "value"}]}], "options": {"javaPackage": "com.google.protobuf", "javaOuterClassname": "WrappersProto", "javaMultipleFiles": true, "goPackage": "google.golang.org/protobuf/types/known/wrapperspb", "ccEnableArenas": true, "objcClassPrefix": "GPB", "csharpNamespace": "Google.Protobuf.WellKnownTypes"}, "syntax": "proto3"}, {"name": "wuxia.proto", "package": "wuxiaworld.api.v2", "dependency": ["google/protobuf/wrappers.proto"], "messageType": [{"name": "NovelChapterInfo", "field": [{"name": "firstChapter", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.ChapterItem", "jsonName": "firstChapter"}, {"name": "latestChapter", "number": 2, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.ChapterItem", "jsonName": "latestChapter"}, {"name": "chapterCount", "number": 3, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".google.protobuf.Int32Value", "jsonName": "chapterCount"}, {"name": "chapterGroups", "number": 4, "label": "LABEL_REPEATED", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.ChapterGroupItem", "jsonName": "chapterGroups"}]}, {"name": "NovelItem", "field": [{"name": "id", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_INT32", "jsonName": "id"}, {"name": "name", "number": 2, "label": "LABEL_OPTIONAL", "type": "TYPE_STRING", "jsonName": "name"}, {"name": "coverUrl", "number": 10, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".google.protobuf.StringValue", "jsonName": "coverUrl"}, {"name": "authorName", "number": 13, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".google.protobuf.StringValue", "jsonName": "authorName"}, {"name": "chapterInfo", "number": 23, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.NovelChapterInfo", "jsonName": "chapterInfo"}]}, {"name": "ChapterItem", "field": [{"name": "entityId", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_INT32", "jsonName": "entityId"}, {"name": "name", "number": 2, "label": "LABEL_OPTIONAL", "type": "TYPE_STRING", "jsonName": "name"}, {"name": "slug", "number": 3, "label": "LABEL_OPTIONAL", "type": "TYPE_STRING", "jsonName": "slug"}, {"name": "content", "number": 5, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".google.protobuf.StringValue", "jsonName": "content"}, {"name": "novelId", "number": 6, "label": "LABEL_OPTIONAL", "type": "TYPE_INT32", "jsonName": "novelId"}, {"name": "translatorThoughts", "number": 19, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".google.protobuf.StringValue", "jsonName": "translatorThoughts"}]}, {"name": "ChapterGroupItem", "field": [{"name": "id", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_INT32", "jsonName": "id"}, {"name": "title", "number": 2, "label": "LABEL_OPTIONAL", "type": "TYPE_STRING", "jsonName": "title"}, {"name": "order", "number": 3, "label": "LABEL_OPTIONAL", "type": "TYPE_INT32", "jsonName": "order"}, {"name": "chapterList", "number": 6, "label": "LABEL_REPEATED", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.ChapterItem", "jsonName": "chapterList"}]}, {"name": "GetChapterByProperty", "field": [{"name": "chapterId", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_INT32", "oneofIndex": 0, "jsonName": "chapterId"}, {"name": "slugs", "number": 2, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.GetChapterByProperty.ByNovelAndChapterSlug", "oneofIndex": 0, "jsonName": "slugs"}], "nestedType": [{"name": "ByNovelAndChapterSlug", "field": [{"name": "novelSlug", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_STRING", "jsonName": "novelSlug"}, {"name": "chapterSlug", "number": 2, "label": "LABEL_OPTIONAL", "type": "TYPE_STRING", "jsonName": "chapterSlug"}]}], "oneofDecl": [{"name": "byProperty"}]}, {"name": "GetNovelRequest", "field": [{"name": "id", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_INT32", "oneofIndex": 0, "jsonName": "id"}, {"name": "slug", "number": 2, "label": "LABEL_OPTIONAL", "type": "TYPE_STRING", "oneofIndex": 0, "jsonName": "slug"}], "oneofDecl": [{"name": "selector"}]}, {"name": "GetNovelResponse", "field": [{"name": "item", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.NovelItem", "jsonName": "item"}]}, {"name": "GetChapterListRequest", "field": [{"name": "novelId", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_INT32", "jsonName": "novelId"}, {"name": "filter", "number": 2, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.GetChapterListRequest.FilterChapters", "jsonName": "filter"}], "nestedType": [{"name": "FilterChapters", "field": [{"name": "chapterGroupId", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".google.protobuf.Int32Value", "jsonName": "chapterGroupId"}, {"name": "isAdvanceChapter", "number": 2, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".google.protobuf.BoolValue", "jsonName": "isAdvanceChapter"}]}]}, {"name": "GetChapterListResponse", "field": [{"name": "items", "number": 1, "label": "LABEL_REPEATED", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.ChapterGroupItem", "jsonName": "items"}]}, {"name": "GetChapterRequest", "field": [{"name": "chapterProperty", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.GetChapterByProperty", "jsonName": "chapterProperty"}]}, {"name": "GetChapterResponse", "field": [{"name": "item", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.ChapterItem", "jsonName": "item"}]}, {"name": "UnlockedItem", "field": [{"name": "novelId", "number": 2, "label": "LABEL_OPTIONAL", "type": "TYPE_INT32", "oneofIndex": 0, "jsonName": "novelId"}, {"name": "chapterId", "number": 3, "label": "LABEL_OPTIONAL", "type": "TYPE_INT32", "oneofIndex": 0, "jsonName": "chapterId"}], "oneofDecl": [{"name": "id"}]}, {"name": "UnlockItemRequest", "field": [{"name": "unlockMethod", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_ENUM", "typeName": ".wuxiaworld.api.v2.UnlockItemMethod", "jsonName": "unlockMethod"}, {"name": "item", "number": 2, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.UnlockedItem", "jsonName": "item"}]}, {"name": "UnlockItemResponse", "field": [{"name": "unlockedItem", "number": 1, "label": "LABEL_OPTIONAL", "type": "TYPE_MESSAGE", "typeName": ".wuxiaworld.api.v2.UnlockedItem", "jsonName": "unlockedItem"}]}], "enumType": [{"name": "UnlockItemMethod", "value": [{"name": "UnlockMethodNone", "number": 0}, {"name": "UnlockMethodKarma", "number": 1}, {"name": "UnlockMethodVip", "number": 2}, {"name": "UnlockMethodSponsor", "number": 3}]}], "service": [{"name": "Novels", "method": [{"name": "GetNovel", "inputType": ".wuxiaworld.api.v2.GetNovelRequest", "outputType": ".wuxiaworld.api.v2.GetNovelResponse"}]}, {"name": "Chapters", "method": [{"name": "GetChapterList", "inputType": ".wuxiaworld.api.v2.GetChapterListRequest", "outputType": ".wuxiaworld.api.v2.GetChapterListResponse"}, {"name": "GetChapter", "inputType": ".wuxiaworld.api.v2.GetChapterRequest", "outputType": ".wuxiaworld.api.v2.GetChapterResponse"}]}, {"name": "Unlocks", "method": [{"name": "UnlockItem", "inputType": ".wuxiaworld.api.v2.UnlockItemRequest", "outputType": ".wuxiaworld.api.v2.UnlockItemResponse"}]}], "publicDependency": [0], "syntax": "proto3"}]}
''')

```
.

![Screenshot_20220829-044408_Termux](https://user-images.githubusercontent.com/50254552/187096543-571cf7d0-7be4-43cd-8aae-011bfd9b49c7.jpg)

**Comment by idMysteries** [comment]
Can you run "lncrawl -lll"?

**Comment by E4rth** [comment]
Can confirm the issue. Here is the log

$ lncrawl.exe -lll
                          [#] Lightnovel Crawler v2.33.0
                  https://github.com/dipu-bd/lightnovel-crawler
                          << LOG LEVEL: DEBUG
2022-08-29 22:50:25,084 [DEBUG] (lncrawl.core.sources)
Loading current index data from C:\Users\Earth\.lncrawl\sources\_index.json
2022-08-29 22:50:25,086 [DEBUG] (lncrawl.core.sources)
Current index was already downloaded once in last 3 hours.
2022-08-29 22:50:25,087 [DEBUG] (lncrawl.core.sources)
Saving current index data to C:\Users\Earth\.lncrawl\sources\_index.json
2022-08-29 22:50:25,122 [DEBUG] (lncrawl.core.sources)
Saving current index data to C:\Users\Earth\.lncrawl\sources\_index.json
2022-08-29 22:50:25,449 [DEBUG] (pyease_grpc.protoc)
No module named 'grpc_tools' Run 'pip install grpcio-tools' to install it. It is required to parse proto files.

-> Press  Ctrl + C  to exit

2022-08-29 22:50:25,833 [INFO] (lncrawl.core.app)
Initialized App
2022-08-29 22:50:25,846 [DEBUG] (asyncio)
Using proactor: IocpProactor
? Enter novel page url or query novel: https://www.wuxiaworld.com/novel/star-odyssey
2022-08-29 22:50:36,914 [INFO] (lncrawl.core.app)
Detected URL input
2022-08-29 22:50:36,915 [INFO] (lncrawl.core.app)
Initializing crawler for: https://www.wuxiaworld.com/ [C:\Users\Earth\.lncrawl\sources\en\w\wuxiacom.py]
? Do you want to log in? Yes
? User/Email: Earth
? Password: ***************
2022-08-29 22:50:48,151 [DEBUG] (lncrawl.core.app)
Login with ('Earth', '*************' (<- intentionally hidden password)) 
Retrieving novel info...
https://www.wuxiaworld.com/novel/star-odyssey
2022-08-29 22:50:48,153 [DEBUG] (821144b6121d076b082b018b43ec8c4e)
Novel slug: star-odyssey
2022-08-29 22:50:48,155 [DEBUG] (urllib3.connectionpool)
Starting new HTTPS connection (1): api.wuxiaworld.com:443
2022-08-29 22:50:48,427 [DEBUG] (urllib3.connectionpool)
https://api.wuxiaworld.com:443 "POST /wuxiaworld.api.v2.Novels/GetNovel HTTP/1.1" 200 None
2022-08-29 22:50:48,429 [INFO] (821144b6121d076b082b018b43ec8c4e)
Novel details: {'id': 117, 'name': 'Star Odyssey', 'coverUrl': 'https://cdn.wuxiaworld.com/images/covers/so.jpg?ver=d7ad422d2f029cc2401cb4f0822af3d2616b804d', 'authorName': 'Along With The Wind (随散飘风)', 'isSneakPeek': False}
2022-08-29 22:50:48,429 [INFO] (821144b6121d076b082b018b43ec8c4e)
Novel title = Star Odyssey
2022-08-29 22:50:48,430 [INFO] (821144b6121d076b082b018b43ec8c4e)
Novel cover = https://cdn.wuxiaworld.com/images/covers/so.jpg?ver=d7ad422d2f029cc2401cb4f0822af3d2616b804d
Traceback (most recent call last):
  File "lncrawl\__main__.py", line 12, in <module>
  File "lncrawl\__init__.py", line 14, in main
  File "lncrawl\core\__init__.py", line 80, in start_app
  File "lncrawl\core\__init__.py", line 77, in start_app
  File "lncrawl\bots\__init__.py", line 17, in run_bot
  File "lncrawl\bots\console\integration.py", line 95, in start
  File "lncrawl\bots\console\integration.py", line 89, in start
  File "lncrawl\bots\console\integration.py", line 78, in _download_novel
  File "lncrawl\core\app.py", line 140, in get_novel_info
  File "C:\Users\Earth\.lncrawl\sources\en\w\wuxiacom.py", line 49, in read_novel_info
    self.novel_author = f"Author: {novel['authorName']}, Translator: {novel['translatorName']}"
KeyError: 'translatorName'
[22060] Failed to execute script '__main__' due to unhandled exception!

**Comment by dipu-bd** [comment]
fixed

**Comment by budikesuma** [comment]
> fixed

@dipu-bd 

Somehow it's still not perfect, I took an example from the novel "Star Odyssey" between chapters 270-300, there are 5 empty chapters.

I made sure it didn't happen to the old file that pydroid3 had customized earlier above.

Test url:

https://www.wuxiaworld.com/novel/star-odyssey

.
![Screenshot_20220830-123657_Termux](https://user-images.githubusercontent.com/50254552/187410106-3658fc0a-f9eb-4f22-824a-3ad924273ab5.jpg)

**Comment by dipu-bd** [comment]
It can happen due to network connection issue.

**Comment by dipu-bd** [comment]
I pushed a new fix. Hope this will solve the issue

**Comment by budikesuma** [comment]
> I pushed a new fix. Hope this will solve the issue

@dipu-bd 

Thanks dev...

The latest fix was successful enough to scrape the chapter body, but a new problem arose.

For chapters that were previously empty (see my SS images above= chapter 275,278,284,287,295), it doesn't display the title name, and only the chapter number.

For me, it's not a big deal, since I can still use the old wuxiacom template quite perfectly (although I have to know the exact range of the last chapter to avoid overlapping advance chapters).

Other fans might have a problem with some blank chapter titles.

.
![Screenshot_20220831-013706_MiXplorer](https://user-images.githubusercontent.com/50254552/187517439-2897ef17-89c1-466f-84c0-ad3a2751bbbc.jpg)
![Screenshot_20220831-013718_MiXplorer](https://user-images.githubusercontent.com/50254552/187517447-06ba30a5-3143-49ed-aeee-e8c2f2c3452a.jpg)

**Comment by dipu-bd** [comment]
It is a intentional feature. The chapter titles that are marked as spoiler are removed. I don't think anyone would complain about it 😄

**Comment by budikesuma** [comment]
> It is a intentional feature. The chapter titles that are marked as spoiler are removed. I don't think anyone would complain about it 😄

@dipu-bd 

Ok...
At least that's not the case with the old wuxiacom script, since my `pyDroid3` is locked to keep using the `old wuxiacom` template. So I can still see all the spoiler chapter title names.

Is that intentional in the `latest wuxiacom` update?

**Comment by dipu-bd** [comment]
It is a intentional feature
